<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WebSchool.Application\WebSchool.Application.csproj" />
    <ProjectReference Include="..\WebSchool.Domain\WebSchool.Domain.csproj" />
    <ProjectReference Include="..\WebSchool.Infra.Data\WebSchool.Infra.Data.csproj" />
  </ItemGroup>

</Project>
